project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!reports/GnC_report/paper/paper_test.qmd"

website:
  title: "ROF Camera Trap Data Exploration"
  sidebar:
    style: "docked"
    contents:
      - href: reports/GnC_report/paper/paper.qmd
        text: GnC Report

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
